### ISSUE TITLE
Dash Emojis for Discord

### ISSUE THREAD

**Issue by coolaj86** [dashtesting-riongull/test-repo-2#1]
Imported from <https://trello.com/c/BhXzmXez/7-dash-emojis-for-discord>.

> Fun bounty (to get things started) to create various Discord emojis

Emoji specs:
- rectangular image 
- use space on to the edges so emoji is maximum size
- basically, look good as an Emoji in Discord

## Production Tasks

- [x] dashtesting/test-repo#1519
- [x] dashtesting/test-repo#1520
- [x] dashtesting/test-repo#1521 
- [ ] dashtesting/test-repo#1

**Comment by riongull** [comment]
Looks like the reference links transferred to point to the new repos
